apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/pv/rabbitmq-log

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/pv/rabbitmq-data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/pv/topic-mongodb
