apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topic-rabbitmq-log-pvc
spec:
  storageClassName: local-storage-class
  volumeName: rabbitmq-log
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topic-rabbitmq-data-pvc
spec:
  storageClassName: local-storage-class
  volumeName: rabbitmq-data
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topic-db-pvc
spec:
  storageClassName: local-storage-class
  volumeName: topic-mongodb
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
