apiVersion: v1
kind: Service
metadata:
  name: gateway-app-service
  labels:
    app: gateway-app-service
spec:
  selector:
    app: gateway-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3001
