apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrator
spec:
  template:
    spec:
      containers:
      - name: prisma-migrator
        image: localhost:5000/filestorage-migrator:latest
        command: ["go", "run", "github.com/steebchen/prisma-client-go", "migrate", "deploy"]
        imagePullPolicy: Never
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: filestorage-config
              key: DB_URL
      restartPolicy: Never
