apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subject-db-pvc
spec:
  volumeName: subject-db
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
