apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  storageClassName: local-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /run/desktop/mnt/host/c/pv/subject-db
