apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-app
  template:
    metadata:
      labels:
        app: subject-app
    spec:
      containers:
      - name: subject-app
        image: jkulrativ/subject-app:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
            name: grpc-port
        
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_USER
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_HOST
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_DBNAME
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_PORT
        - name: POSTGRES_SSL_MODE
          valueFrom:
            configMapKeyRef:
              name: subject-service-config
              key: POSTGRES_SSL_MODE
