apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/subject-db
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/minio
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-db-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/filestorage-db
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/rabbitmq/log
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/rabbitmq/data
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /pv/topic-db
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com
