apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-04c306149824e561d.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-0f5db71c21b0d36bd.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-db-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-0ef5ae3a085579ce6.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-0e82938b8d854e6c6.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-0d816449d2c0281a7.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /
    server: fs-0baaf0d7bbde4a53c.efs.us-east-1.amazonaws.com
