apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-0364376c9187d5150

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-0ee262f21b59b3ee7

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-db-pv
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-0cc3266c7d707fd83

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-0998d7795783dccc8

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-04220fbc2bd52a41b

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f:/fsap-0658ce78f2b2d00a1
