apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-db-pv
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c9dcc2475f10ae6f
