apiVersion: v1
kind: PersistentVolume
metadata:
  name: subject-db
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  nfs:
    path: "/subject-db"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - tls
  nfs:
    path: "/minio"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestorage-db-pv
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/filestorage-db"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-log
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/rabbitmq-log"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-data
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/rabbitmq-data"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: topic-mongodb
spec:
  storageClassName: local-storage-class
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/topic-db"
    server: fs-0c9dcc2475f10ae6f.efs.us-east-1.amazonaws.com
