apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cu-overflow-ingress

spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway-app-service
            port:
              number: 8000
