apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cu-overflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
  - secretName: ingress-cert
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: gateway-app-service
            port:
              number: 3001
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-service
            port:
              number: 8080
