apiVersion: v1
kind: Pod
metadata:
  name: subject-app
  labels:
    app: subject-app
spec:
  containers:
  - name: subject-app
    image: cu-overflow/subject:latest
    imagePullPolicy: Never
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        name: grpc-port
    
    env:
    - name: POSTGRES_USER
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_USER
    - name: POSTGRES_HOST
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_HOST
    - name: POSTGRES_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_DBNAME
    - name: POSTGRES_PORT
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_PORT
    - name: POSTGRES_SSL_MODE
      valueFrom:
        configMapKeyRef:
          name: subject-app-secret
          key: POSTGRES_SSL_MODE
